Repository bookbok/bookbok, pull requests merged in 2018-12, with the labels that each got.

#127 Add fetch wrapper
  resources/js/actions.js
  resources/js/components/Header.jsx
  resources/js/index.js
  resources/js/utils.js
Labels: Frontend, enhancement :muscle:

#132 Add likes api
  app/Http/Controllers/LikeController.php
  routes/api.php
Labels: Backend

#133 国会図書館APIを叩いてスクレイプマネージャにBookを返すクラス実装#72
  app/Components/BookInfoScraper/GoogleBooksScraper.php
  app/Components/BookInfoScraper/NationalDietLibraryScraper.php
  app/Providers/BookInfoScraperServiceProvider.php
Labels: Backend

#134 Fix book primary key
  app/Http/Controllers/BookController.php
  app/Http/Controllers/BookUserController.php
  app/User.php
  database/migrations/2018_11_02_133709_create_books_table.php
  database/seeds/UserBooksTableSeeder.php
Labels: Backend

#138 Update action type
  resources/js/actions.js
  resources/js/reducers.js
  resources/js/types.js
Labels: Frontend

#157 Fix like love table
  app/Bok.php
  app/Book.php
  app/BookUser.php
  app/Http/Controllers/ReactionController.php
  app/Providers/AppServiceProvider.php
  app/Reaction.php
  app/User.php
  database/migrations/2018_12_06_113700_create_reactions_table.php
  database/seeds/DatabaseSeeder.php
  database/seeds/ReactionsTableSeeder.php
  docs/api.md
  routes/api.php
Labels: Backend

#167 Fix query logger
  app/Providers/AppServiceProvider.php
  database/factories/ReviewFactory.php
Labels: Backend

#168 Revert to user book
  app/Bok.php
  app/Book.php
  app/Http/Controllers/UserBookController.php
  app/Review.php
  app/User.php
  app/UserBook.php
  database/migrations/2018_11_02_143901_create_user_books_table.php
  database/migrations/2018_11_02_144546_create_reviews_table.php
  database/migrations/2018_11_04_014744_create_boks_table.php
  database/seeds/BoksTableSeeder.php
  database/seeds/ReviewsTableSeeder.php
  database/seeds/UserBooksTableSeeder.php
  docs/api.md
  routes/api.php
  tests/Controllers/BookUserControllerTest.php
Labels: Backend

#186 Fix response body
  app/User.php
Labels: Backend

#179 Add auth prefix
  resources/js/actions.js
Labels: Frontend

#201 ユーザブックのBOKSを返すAPIの実装#165
  app/Http/Controllers/BokController.php
  routes/api.php
Labels: Backend

#205 メールアドレス検証機能の追加
  app/Http/Controllers/Auth/VerificationController.php
  app/Notifications/VerifyEmail.php
  app/User.php
  docs/api.md
  routes/api.php
  routes/web.php
Labels: Backend

#209 BOKフローを返すAPI実装#202
  app/Http/Controllers/BokController.php
  app/Http/Controllers/BokFlowController.php
  docs/api.md
  routes/api.php
Labels: Backend

#210 Add user book detail
  app/Http/Controllers/UserBookController.php
  resources/js/actions.js
  resources/js/components/Header.jsx
  resources/js/components/Mypage.jsx
  resources/js/components/UserBookDetail.jsx
  resources/js/containers.js
  resources/js/reducers.js
  resources/js/types.js
  resources/sass/_book_detail.scss
  resources/sass/_booklist_view.scss
  resources/sass/_responsive.scss
  resources/sass/_user_info.scss
  resources/sass/_variables.scss
  resources/sass/app.scss
Labels: Frontend

#226 Add bok flow view
  resources/js/actions.js
  resources/js/components/BokFlow.jsx
  resources/js/components/Header.jsx
  resources/js/components/TimeLine.jsx
  resources/js/containers.js
  resources/js/reducers.js
  resources/js/types.js
Labels: Frontend

#217 Add [user ]book detail link
  resources/js/actions.js
  resources/js/components/BookListView.jsx
  resources/js/components/BookView.jsx
  resources/js/components/Header.jsx
  resources/js/components/UserBookshelf.jsx
  resources/js/components/UsersBookshelf.jsx
  resources/js/containers.js
  resources/js/reducers.js
  resources/js/types.js
Labels: Frontend

#222 Update user book detail component
  resources/js/components/BookDetailView.jsx
  resources/js/components/UserBookDetail.jsx
  resources/js/components/shared/book/BookInfo.jsx
  resources/js/components/shared/user/FloatUserInfo.jsx
Labels: Frontend

#223 Add status to userbook
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/BokFlowController.php
  app/Http/Controllers/ReviewController.php
  app/Http/Controllers/UserBookController.php
  app/Review.php
  app/User.php
  app/UserBook.php
  database/migrations/2018_11_02_143901_create_user_books_table.php
  database/migrations/2018_11_02_144546_create_reviews_table.php
  database/migrations/2018_11_04_014744_create_boks_table.php
  docs/api.md
  routes/api.php
Labels: Backend

#234 GoogoleBooksScraperのサブタイトル対応#227
  app/Components/BookInfoScraper/GoogleBooksScraper.php
Labels: Backend

#244 Update users view
  resources/js/actions.js
  resources/js/components/Header.jsx
  resources/js/components/UserInfo.jsx
  resources/js/components/UsersView.jsx
  resources/js/containers.js
  resources/js/reducers.js
  resources/js/types.js
Labels: Frontend

#249 Add bok post controller
  app/Bok.php
  app/Http/Controllers/BokController.php
  routes/api.php
Labels: Backend

#258 Google books scraperのベースuri修正#257
  app/Components/BookInfoScraper/GoogleBooksScraper.php
Labels: Backend

#266 クラスのとじ括弧が消えていたので修正
  app/Http/Controllers/LikeController.php
  app/Http/Controllers/ReviewController.php
Labels: Backend

#261 Add user book from isbn
  app/Http/Controllers/UserBookController.php
  resources/js/actions.js
  resources/js/components/BookListView.jsx
  resources/js/components/Genres.jsx
  resources/js/components/Search.jsx
  resources/js/components/shared/book/ISBNModal.jsx
  resources/sass/_search_component.scss
  resources/sass/app.scss
  routes/api.php
Labels: Backend, Frontend

#265 Update user detail
  resources/js/components/UserDetail.jsx
  resources/js/utils.js
Labels: Frontend

#279 ユーザーブックにネタバレフラグを追加
  app/Genre.php
  app/Http/Controllers/UserBookController.php
  app/User.php
  app/UserBook.php
  database/migrations/2018_12_18_145324_add_spoiler_flag_column__user_books_table.php
  docs/api.md
Labels: Backend

#284 ISBN::normalize()が文字列がISBNとして扱えない場合にスローする例外のハンドリング
  app/Http/Controllers/UserBookController.php
Labels: Backend

#293 やべーよやべーよ、認証ユーザーの取得方法が間違ってんよ〜
  app/Http/Controllers/BokController.php
  app/Http/Controllers/BokFlowController.php
  app/Http/Controllers/LikeController.php
  app/Http/Controllers/UserBookController.php
  app/User.php
  database/seeds/DatabaseSeeder.php
  database/seeds/LikesTableSeeder.php
  database/seeds/LovesTableSeeder.php
  resources/js/components/BookView.jsx
Labels: Backend

#296 同じ本を本棚に登録しようとしたときの例外処理#259
  app/Http/Controllers/UserBookController.php
Labels: Backend

#294 Add loves api
  app/Http/Controllers/ReactionController.php
  app/User.php
  routes/api.php
Labels: Backend

#292 fetch関数を良い感じにしちゃった
  resources/js/actions.js
  resources/js/utils.js
Labels: Frontend

#304 ユーザの情報を出す際にメールアドレスは基本的に出さないようにした
  app/User.php
  routes/api.php
Labels: Backend

#303 Fix bok controller
  app/Bok.php
  app/Http/Controllers/BokController.php
  app/Http/Controllers/ReviewController.php
  docs/api.md
Labels: Backend

#281 Add search books request
  resources/js/actions.js
  resources/js/components/BookListView.jsx
  resources/js/components/Search.jsx
  resources/js/utils.js
Labels: Frontend, enhancement :muscle:

#301 Fix isbn modal
  app/Http/Controllers/UserBookController.php
  resources/js/components/shared/book/ISBNModal.jsx
  resources/js/utils.js
Labels: Frontend

#305 Add followers & followings api
  app/Follower.php
  app/Http/Controllers/FollowerController.php
  app/User.php
  docs/api.md
  routes/api.php
Labels: Backend

#306 Add follow action
  resources/js/actions.js
  resources/js/components/shared/user/FloatUserInfo.jsx
  resources/js/components/shared/user/FollowButton.jsx
Labels: Frontend

#319 User follow info #317
  app/Helpers/AuthHelper.php
  app/Http/Controllers/UserController.php
  app/Providers/HelperServiceProvider.php
  app/User.php
  config/app.php
  docs/api.md
  routes/api.php
Labels: Backend

#313 Add follow component
  resources/js/components/FollowersView.jsx
  resources/js/components/FollowingsView.jsx
  resources/js/components/Header.jsx
  resources/js/components/shared/user/FloatUserInfo.jsx
Labels: Frontend

#314 Add update user book#310
  app/Http/Controllers/UserBookController.php
  app/UserBook.php
  docs/api.md
  routes/api.php
Labels: =please review=, Backend

#322 Add json unescape middleware
  app/Http/Controllers/BokController.php
  app/Http/Controllers/BokFlowController.php
  app/Http/Controllers/BookController.php
  app/Http/Controllers/FollowerController.php
  app/Http/Controllers/GenreController.php
  app/Http/Controllers/ReactionController.php
  app/Http/Controllers/ReviewController.php
  app/Http/Controllers/UserBookController.php
  app/Http/Controllers/UserController.php
  app/Http/Kernel.php
  app/Http/Middleware/UnescapeJsonResponse.php
Labels: =please review=, Backend

#323 Update user book struct
  app/Http/Controllers/UserBookController.php
Labels: =please review=, Backend

#324 Add auth check
  app/Http/Controllers/ReviewController.php
  routes/api.php
Labels: Backend

#328 Add user view
  app/User.php
  resources/js/components/shared/user/FloatUserInfo.jsx
  resources/js/components/shared/user/FollowButton.jsx
Labels: Backend, Frontend
