Repository bookbok/bookbok, pull requests merged in 2019-01, with the labels that each got.

#333 Add followers & followings view component
  resources/js/actions.js
  resources/js/components/FollowersView.jsx
  resources/js/components/FollowingsView.jsx
  resources/js/components/shared/user/MyPageTabs.jsx
  resources/js/components/shared/user/SimpleUser.jsx
  resources/js/reducers.js
  resources/js/types.js
  resources/sass/_user_info.scss
Labels: =please review=, Frontend

#339 Add user book update
  app/Http/Controllers/UserBookController.php
  resources/js/actions.js
  resources/js/components/App.jsx
  resources/js/components/Header/index.js
  resources/js/components/RouterWithHeader.jsx
  resources/js/components/UserBookDetail.jsx
  resources/js/components/UserBookDetail/UserBookInfo.jsx
  resources/js/components/UserBookDetail/index.js
  resources/js/components/shared/book/BookInfo.jsx
  resources/js/containers.js
Labels: Backend, Frontend

#348 フォロー系一覧APIに認証ユーザとのフォロー関係を示すパラメータを追加した
  app/Http/Controllers/FollowerController.php
  app/User.php
  docs/api.md
Labels: Backend

#350 本のジャンル取得#290
  app/Components/BookInfoScraper/ScrapeManager.php
  app/Genre.php
  app/Providers/BookInfoScraperServiceProvider.php
  database/seeds/GenresTableSeeder.php
Labels: Backend

#349 ユーザ一覧で不要な外部結合があったので削除した
  app/User.php
Labels: Backend

#356 json_decodeのエラーハンドリングを追加したよ
  app/Components/BookInfoScraper/GoogleBooksScraper.php
  app/Components/BookInfoScraper/NationalDietLibraryScraper.php
  app/Components/BookInfoScraper/ScrapeManager.php
Labels: Backend

#370 MySQLの制約回避
  app/Providers/AppServiceProvider.php
Labels: Backend, bug :scream:

#373 Fix bok flow access
  resources/js/components/BokFlow/index.js
  resources/js/components/RouterWithHeader.jsx
  resources/js/containers.js
Labels: Frontend

#391 Fix bok flow
  public/css/app.css
  public/js/app.js
  resources/js/components/BokFlow/index.js
Labels: Frontend

#394 Fix down migration
  database/migrations/2018_11_02_134419_add_role_to_users.php
Labels: Backend

#405 Add no image book view
  resources/js/components/BookListView.jsx
  resources/js/components/BookView.jsx
  resources/js/components/RouterWithHeader.jsx
  resources/js/components/UserBookshelf.jsx
  resources/js/containers.js
  resources/sass/_booklist_view.scss
Labels: Frontend

#419 Update loading method
  resources/js/actions.js
  resources/js/components/BookListView/BooksSuspense.jsx
  resources/js/components/BookListView/index.js
Labels: Frontend

#422 HTTPでアクセスしてきたらHTTPSにリダイレクトさせる処理をミドルウェアで対応する#418
  app/Http/Kernel.php
  app/Http/Middleware/ForceHttps.php
  app/Providers/ForceHttpsProvider.php
  config/https.php
Labels: Backend

#415 ソーシャルログインapiを追加
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/SocialController.php
  composer.json
  composer.lock
  config/services.php
  database/migrations/2019_01_11_134414_prepare_users_table_for_social_authentication.php
  docs/api.md
  routes/api.php
Labels: Backend

#425 ユーザ情報更新apiを追加
  app/Http/Controllers/Auth/UserController.php
  docs/api.md
  routes/api.php
Labels: Backend

#410 Fix when miss login
  resources/js/actions.js
  resources/js/components/Login.jsx
Labels: Frontend

#432 Add paginator
  package-lock.json
  package.json
  resources/js/actions.js
  resources/js/components/BookListView/BooksSuspense.jsx
  resources/js/components/BookListView/index.js
  resources/js/reducers.js
  resources/js/types.js
  resources/sass/_booklist_view.scss
Labels: Frontend

#437 fix#434
  app/Http/Middleware/ForceHttps.php
Labels: Backend, bug :scream:

#439 バリデーションエラーメッセージの日本語化
  resources/lang/ja/auth.php
  resources/lang/ja/pagination.php
  resources/lang/ja/passwords.php
  resources/lang/ja/validation.php
Labels: Backend

#444 楽天API使用の有効化#443
  app/Components/BookInfoScraper/ScrapeManager.php
Labels: Backend

#445 本の必須情報をとれない無能スクレイパーは無視されるように修正
  app/Components/BookInfoScraper/ScrapeManager.php
Labels: Backend

#446 ページをリロードしてもログイン状態を継続する機能の追加
  resources/js/actions.js
  resources/js/index.js
  resources/js/utils.js
Labels: Frontend

#457 Add js versioning
  resources/views/layouts/app.blade.php
  webpack.mix.js
Labels: Frontend

#463 ユニークルールを外し、バリデーション実行後に名前の有効性チェックを行うように変更
  app/Http/Controllers/Auth/UserController.php
Labels: Backend, bug :scream:

#462 Adapt feedback
  resources/js/components/BokFlow/BokFlowContent.jsx
  resources/js/components/BokFlow/index.js
  resources/js/components/Footer.jsx
  resources/js/components/Header/index.js
  resources/js/components/Login.jsx
  resources/js/components/UserDetail.jsx
  resources/js/components/UserRegister.jsx
Labels: Frontend

#465 CSV形式で書籍を読み込む#436
  app/Components/ISBN.php
  app/Http/Controllers/ImportBooksController.php
  app/UserBook.php
  docs/api.md
  routes/api.php
Labels: Backend

#468 boksの流れが分かりやすくなるように縦線を追加
  resources/js/components/UserBookDetail/index.js
  resources/sass/_userdetail_bok.scss
Labels: Frontend

#472 Fix multi routes component
  app/User.php
  resources/js/actions.js
  resources/js/components/Home.jsx
  resources/js/components/Login.jsx
  resources/js/components/RouterWithHeader.jsx
  resources/js/components/UserBookshelf.jsx
  resources/js/components/UserDetail.jsx
  resources/js/containers.js
  resources/js/decorators/FetchOnIdUpdateDecorator.jsx
  resources/js/reducers.js
  resources/js/types.js
  webpack.mix.js
Labels: Frontend

#470 Bokを削除するapi実装#469
  app/Http/Controllers/BokController.php
  docs/api.md
  routes/api.php
Labels: Backend

#475 Update design
  resources/js/components/BookDetailView.jsx
  resources/js/components/Header/index.js
  resources/js/components/UserBookDetail/index.js
  resources/sass/_root.scss
  resources/sass/_userdetail_bok.scss
  resources/sass/app.scss
Labels: Frontend

#486 Add loading flag
  resources/js/actions.js
  resources/js/components/LikeBokList.jsx
  resources/js/components/LoveBokList.jsx
  resources/js/components/RouterWithHeader.jsx
  resources/js/containers.js
Labels: Frontend

#492 Refactor component
  docs/code_terms.md
  resources/js/components/App.jsx
  resources/js/components/App/Footer.jsx
  resources/js/components/App/Header.jsx
  resources/js/components/App/Routes.jsx
  resources/js/components/App/index.js
  resources/js/components/IsbnBulkRegistrationView.jsx
  resources/js/components/RouterWithHeader.jsx
  resources/js/index.js
Labels: Frontend, Refactor :pill:

#494 画像URLを一律1000文字まで格納できるように変更
  app/Http/Controllers/Auth/UserController.php
  database/migrations/2019_01_29_101422_alter_image_url_column_max_length.php
Labels: Backend

#495 Add isbn list
  app/Http/Controllers/ImportBooksController.php
  resources/js/actions.js
  resources/js/components/App/Header.jsx
  resources/js/components/App/Routes.jsx
  resources/js/components/IsbnBulkRegistrationView.jsx
Labels: Backend, Frontend, enhancement :muscle:

#501 Update genres component in book list page
  resources/js/components/BookListView/BooksSuspense.jsx
  resources/js/components/BookListView/index.js
  resources/js/components/Genres.jsx
  resources/js/components/shared/book/ISBNModal.jsx
  resources/js/containers.js
Labels: Frontend

#505 Update footer
  resources/js/components/App/Footer.jsx
  resources/sass/_footer.scss
Labels: Frontend

#506 Update back button
  resources/js/components/BookDetailView.jsx
  resources/js/components/IsbnBulkRegistrationView.jsx
  resources/js/components/UserBookDetail/index.js
  resources/js/components/shared/BackButtonArea.jsx
Labels: Frontend

#510 Update design & Fix user update
  resources/js/components/PrivacyPolicyView.jsx
  resources/js/components/TermsOfServiceView.jsx
  resources/js/components/UserDetail.jsx
  resources/sass/_policies.scss
  resources/sass/app.scss
Labels: Frontend
