Repository bookbok/bookbok, pull requests merged in 2019-02, with the labels that each got.

#515 Fix review modal
  resources/js/components/UserBookDetail/BokModal.jsx
  resources/js/components/UserBookDetail/ReviewModal.jsx
  resources/js/components/UserBookDetail/index.js
Labels: Frontend

#516 Add bok id anchor in page
  resources/js/components/UserBookDetail/index.js
Labels: Frontend

#520 Add default user icon
  resources/js/components/UsersView.jsx
  resources/js/components/shared/user/DefaultAvatar.jsx
  resources/js/components/shared/user/FloatUserInfo.jsx
  resources/js/components/shared/user/SimpleUser.jsx
  resources/sass/_user_info.scss
Labels: Frontend

#527 Add the delete bok method
  resources/js/actions.js
  resources/js/components/UserBookDetail/index.js
  resources/js/reducers.js
  resources/js/types.js
  resources/js/utils.js
Labels: Frontend

#541 User bookの削除api#471
  app/Http/Controllers/UserBookController.php
  docs/api.md
  routes/api.php
Labels: Backend

#540 Add pulldown to bok
  resources/js/actions.js
  resources/js/components/UserBookDetail/UserDetailBok.jsx
  resources/js/components/UserBookDetail/index.js
  resources/js/utils.js
Labels: Frontend

#542 レビュータイトルを追加した
  app/Http/Controllers/BookController.php
  app/Http/Controllers/ReviewController.php
  app/Review.php
  app/UserBook.php
  database/migrations/2019_02_05_105624_add_review_title_column_review_table.php
  docs/api.md
  resources/js/components/UserBookDetail/ReviewModal.jsx
  resources/js/components/UserBookDetail/index.js
Labels: Backend, Frontend

#544 Fix add to shelf
  resources/js/components/AlertView.jsx
  resources/js/components/App/index.js
  resources/js/components/Bok.jsx
  resources/js/components/BokFlow/index.js
  resources/js/components/BookDetailView.jsx
  resources/js/components/FlashMessages/Alert.jsx
  resources/js/components/FlashMessages/index.js
  resources/js/components/UserBookDetail/UserDetailBok.jsx
  resources/js/components/shared/book/ISBNModal.jsx
  resources/js/components/shared/user/FloatUserInfo.jsx
  resources/sass/_toast.scss
  resources/sass/app.scss
Labels: Frontend

#546 Add bok modal init state
  resources/js/components/UserBookDetail/BokModal.jsx
Labels: Frontend

#553 メールアドレスが未検証の場合はログインを認めないように修正
  app/Http/Controllers/Auth/LoginController.php
Labels: Backend

#554 composer install時に実行するマイグレーション処理を強制実行(非対話)に変更
  composer.json
Labels: Backend

#560 Update user book info manage to state
  resources/js/components/UserBookDetail/index.js
Labels: Frontend

#573 Update books search box
  resources/js/components/BookListView/Genres.jsx
  resources/js/components/BookListView/Search.jsx
  resources/js/components/BookListView/index.js
Labels: Frontend

#570 Fix redirect home when logout
  resources/js/actions.js
  resources/js/components/Logout.jsx
Labels: Frontend

#567 Add prepared flag
  resources/js/actions.js
  resources/js/components/App/Header.jsx
  resources/js/components/App/index.js
  resources/js/index.js
  resources/js/reducers.js
  resources/js/types.js
Labels: Frontend

#565 Fix bok menu handle
  resources/js/components/UserBookDetail/UserDetailBok.jsx
Labels: Frontend

#569 Add const id to genres
  database/seeds/GenresTableSeeder.php
Labels: Backend

#555 Add config page#522
  resources/js/actions.js
  resources/js/components/App/Header.jsx
  resources/js/components/App/Routes.jsx
  resources/js/components/Config.jsx
  resources/js/components/UserDetail.jsx
  resources/sass/_user_info.scss
Labels: Frontend

#574 Add tutorial page
  public/images/tutorials/01-01.png
  public/images/tutorials/01-02.png
  public/images/tutorials/01-03.png
  public/images/tutorials/01-04.png
  public/images/tutorials/01-05.png
  public/images/tutorials/02-01.png
  public/images/tutorials/02-02.png
  public/images/tutorials/02-03.png
  public/images/tutorials/02-04.png
  public/images/tutorials/03-01.png
  public/images/tutorials/03-02.png
  public/images/tutorials/03-03.png
  public/images/tutorials/03-04.png
  public/images/tutorials/04-01.png
  public/images/tutorials/04-02.png
  resources/js/actions.js
  resources/js/components/App/Routes.jsx
  resources/js/components/BookDetailView.jsx
  resources/js/components/Config.jsx
  resources/js/components/FollowersView.jsx
  resources/js/components/FollowingsView.jsx
  resources/js/components/IsbnBulkRegistrationView.jsx
  resources/js/components/Tutorial/ImageCard.jsx
  resources/js/components/Tutorial/Tutorial00.jsx
  resources/js/components/Tutorial/Tutorial01.jsx
  resources/js/components/Tutorial/Tutorial02.jsx
  resources/js/components/Tutorial/Tutorial03.jsx
  resources/js/components/Tutorial/Tutorial04.jsx
  resources/js/components/Tutorial/index.js
  resources/js/components/UserBookDetail/index.js
  resources/js/components/UserBookshelf.jsx
  resources/js/components/UserDetail.jsx
  resources/js/components/shared/user/FloatUserInfo.jsx
  resources/sass/_book_detail.scss
  resources/sass/_page_content_styles.scss
  resources/sass/app.scss
Labels: Frontend
